### ISSUE TITLE
Hitting limit on prebid cache server for video responses

### ISSUE THREAD

**Issue by ouimet51** [prebid/prebid-cache#20]
The prebid cache server has a limit of 10kb per value passed to the server, if the file goes over the limit there will be a 400 error thrown from the server. For video publishers, the XML file can get over this range pretty frequently leaving bidders our of the competition. We should add compression or raise the limit to the server so temporary storage is used for all video programmatic partners. I can add

**Comment by dbemiller** [comment]
That would be great, thanks!

We actually do have compression (see the `project-root/compression` directory)... but it looks like the max length limit occurs _before_ compression gets applied.

We could either raise the limit, move the length check so that it happens _after_ compression, or both. Anything you want to contribute here would be helpful ^^.

**Comment by jbartek25** [comment]
@dbemiller Apologies if my question is off-topic here but I didn't find a better place to ask: if a PR concerning the limit is merged will the change be deployed to Appnexus' Prebid server cache instance https://prebid.adnxs.com/pbc/v1/cache?

**Comment by dbemiller** [comment]
@jbartek25 yes it will

**Comment by jbartek25** [comment]
@dbemiller great! thank you!
I'm interested to see what size limit you will settle on - please let us know (in this thread?). Although I understand your colleague's reasoning about lower predictability when the limit is applied after compression, I still think it would make more sense to check compressed size because since the cache is a simple key-value storage, the value can be anything - currently natives and VAST XML but who knows what else in the future so the better compressible data should be allowed to have bigger raw size. For example VAST XML served by our ad server (Improve Digital) contains 20 tracking events pointing to very similar URLs and hence the gzip compression ratio is 8:1. From my perspective I don't need to predict whether a payload is too big for the cache or not on a continuous basis but rather as a one-off exercise to measure the average size of payload. Just my 2c. Thanks again for your work.

**Comment by dbemiller** [comment]
@jbartek25 sure thing. I probably shouldn't have closed this, if there was followup to be done.

You make a good case here for setting the limits post-compression. I'll talk it over here.

Are you planning to contribute a gzip compression module to the project? That would be pretty awesome :)

**Comment by hhhjort** [comment]
My initial thought is having the limit pre-compression is better for predictability as well. However I started thinking who would actually be doing the predicting? The publisher cannot predict what the bidders might bid. The bidders will not, in general, have access to the cache limit, or even any clear signal if their content will need to be cached in the first place. So predictability in this case is not actually a useful feature. I suppose we could add some sort of signaling to `ext` for the bidders to alert them to cache limits, but I doubt there will be much support to read this on the bidder side.

This leaves the limit being used just to prevent some oversized requests from eating all the cache space, in which case limiting on compressed size is if anything better than limiting compressed size.

**Comment by dbemiller** [comment]
@harbinha we did bump it to 20k. The config file in this repo is just for example... each deployment will have its own values.

I'll look into it again when I have time... but after bumping it to 20k, our metrics were showing 99.9% of the requests succeeding. If that's a major problem for you, we can look into bumping it higher... but assuming no bugs, the vast majority of the requests should be succeeding.

**Comment by dbemiller** [comment]
errr.... scratch that. I just checked again, and our metrics must have shifted over time. The p95 is now ~26K, so we are probably rejecting a significant number of payloads.

I'm in the middle of something at the moment... but will release & bump it again this afternoon.

**Comment by dbemiller** [comment]
Sorry for the delay... it's now at 40K, so the % of failed requests should now be very small (definitely somewhere between 0.1% and 1%... but most likely closer to 0.1 than 1)
