### ISSUE TITLE
Misleading metrics when custom key used

### ISSUE THREAD

**Issue by jbartek25** [prebid/prebid-cache#86]
From README:

> ...a cache key can be specified for the cached object. If an entry already exists for "ArbitraryKeyValueHere", it will not be overwitten, and "" will be returned for the uuid value of that entry. This is to prevent bad actors from trying to overwrite legitimate caches...

To achieve the above, code [here](https://github.com/prebid/prebid-cache/blob/master/endpoints/put.go#L98) first calls the `Get` method to check if the key already exists in cache. The downside of this approach is that the `Get` check leads to a large number of Get errors (PBC `prebid_cache_gets_backend{status="error"}` metric) and Get misses (backend storage metric, in my case Memcached). Also there's a question of efficiency: Get + Put is certainly more expensive than a single operation which only writes the item if the key doesn't exist in cache.

I'm currently testing with Memcached removing the check for key existence and replacing the Memcached `Set` method used by Put with `Add` method which only writes the item if the key hasn't been set already. With no other code change, an attempt to write value for an existing key will end up with response 500 and message `memcache: item not stored`. It will work fine for my use case but it's no acceptable as a general fix as it changes the API (no error + empty uuid for existing entry).

**Comment by SyntaxNode** [comment]
Agreed.

Additionally, the call to verify the key doesn't exist before writing is not atomic and potentially subject to race conditions - although we don't really see that in practice.

We started working on a redesign for this last week. The hard part is implementing the change for all 5 data sources, since we personally just use Aerospike. Perhaps we can first roll out improvements for Aerospike and Memcache and add other data sources soon after.

If we provide a framework for making the change, would be willing to implement and test the new approach for Memcache?

**Comment by jbartek25** [comment]
> We started working on a redesign for this last week.
Great :-)

> would be willing to implement and test the new approach for Memcache
Yes sure

**Comment by guscarreon** [comment]
@jbartek25 thank you for pointing this defect out. We had been planning to correct this issue in the past and now a pull request draft has been posted. It still needs work, but soon it'll be complete. Please let us know your thoughts on it.

**Comment by SyntaxNode** [comment]
Thank you for your patience. This issue has been addressed in release 0.14.0.
